git:
  submodules: false
jobs:
  allow_failures:
    - stage: deploy
      name: Snap arm64
  include:
    - <<: *linux
      python: "3.7"
    - <<: *linux
      python: "3.8"
    - <<: *linux
      python: "3.9"
    - <<: *linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      python: "3.7"
    - <<: *linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      python: "3.8"
    - <<: *linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      python: "3.9"
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
